/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class Change : TBase
{
  private @Value _Key;
  private @Value _Value;

  public @Value Key
  {
    get
    {
      return _Key;
    }
    set
    {
      __isset.Key = true;
      this._Key = value;
    }
  }

  public @Value Value
  {
    get
    {
      return _Value;
    }
    set
    {
      __isset.@Value = true;
      this._Value = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool Key;
    public bool @Value;
  }

  public Change() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Struct) {
            Key = new @Value();
            Key.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.Struct) {
            Value = new @Value();
            Value.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("Change");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Key != null && __isset.Key) {
      field.Name = "Key";
      field.Type = TType.Struct;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      Key.Write(oprot);
      oprot.WriteFieldEnd();
    }
    if (Value != null && __isset.@Value) {
      field.Name = "Value";
      field.Type = TType.Struct;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      Value.Write(oprot);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("Change(");
    bool __first = true;
    if (Key != null && __isset.Key) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Key: ");
      __sb.Append(Key== null ? "<null>" : Key.ToString());
    }
    if (Value != null && __isset.@Value) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Value: ");
      __sb.Append(Value== null ? "<null>" : Value.ToString());
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

