/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class NodeChanges : TBase
{
  private int _Node;
  private List<Change> _Changes;

  public int Node
  {
    get
    {
      return _Node;
    }
    set
    {
      __isset.Node = true;
      this._Node = value;
    }
  }

  public List<Change> Changes
  {
    get
    {
      return _Changes;
    }
    set
    {
      __isset.Changes = true;
      this._Changes = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool Node;
    public bool Changes;
  }

  public NodeChanges() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.I32) {
            Node = iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.List) {
            {
              Changes = new List<Change>();
              TList _list0 = iprot.ReadListBegin();
              for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
              {
                Change _elem2;
                _elem2 = new Change();
                _elem2.Read(iprot);
                Changes.Add(_elem2);
              }
              iprot.ReadListEnd();
            }
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("NodeChanges");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.Node) {
      field.Name = "Node";
      field.Type = TType.I32;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(Node);
      oprot.WriteFieldEnd();
    }
    if (Changes != null && __isset.Changes) {
      field.Name = "Changes";
      field.Type = TType.List;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.Struct, Changes.Count));
        foreach (Change _iter3 in Changes)
        {
          _iter3.Write(oprot);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("NodeChanges(");
    bool __first = true;
    if (__isset.Node) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Node: ");
      __sb.Append(Node);
    }
    if (Changes != null && __isset.Changes) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Changes: ");
      __sb.Append(Changes);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

